In [1]:
import pandas as pd
import numpy as np
import os
from sklearn.cluster import KMeans

In [2]:
os.chdir("/home/geanderson/Dropbox/APPS/data")

In [3]:
df = pd.read_csv('retail_july.csv')

In [4]:
df.columns.sort_values().values

array(['AbandonedCart', 'AcceptAD', 'AcceptDiscount', 'AddtoCart',
       'BuyOrNot', 'Category', 'Churn', 'Clustering',
       'CompetitionPressure', 'Country', 'CustomerID', 'Date',
       'DaysLastOrder', 'Description', 'Display', 'DisplayInStore',
       'Elasticity', 'InvoiceDate', 'InvoiceNo', 'KindOfSale',
       'LenghtDiscount', 'NormalPrice', 'Payment', 'PromotionDays',
       'Quantity', 'ReOrder', 'RePurchase', 'Revenue', 'Seasonality',
       'StockCode', 'Time', 'TypeofProduct', 'TypeofPromotion',
       'UnitPrice', 'Weather', 'day_of_week'], dtype=object)

In [5]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(np.array(df.Category.values))
le.transform(np.array(df.Category.values))


array([0, 2, 2, ..., 1, 3, 1])

In [6]:
df['One_Hot_Category'] = le.transform(np.array(df.Category.values))

In [31]:
X = df[['Revenue', 'One_Hot_Category', 'LenghtDiscount', 'Quantity', 'NormalPrice']]

In [32]:
min_max_scaler = preprocessing.MinMaxScaler()
X_minmax = min_max_scaler.fit_transform(X)
X_minmax

array([[0.5 , 0.  , 0.8 , 0.5 , 0.74],
       [0.5 , 0.67, 0.82, 0.5 , 0.07],
       [0.5 , 0.67, 0.08, 0.5 , 0.34],
       ...,
       [0.5 , 0.33, 0.71, 0.5 , 0.76],
       [0.5 , 1.  , 0.97, 0.5 , 0.26],
       [0.5 , 0.33, 0.48, 0.5 , 0.13]])

In [33]:
kmeans2 = KMeans(n_clusters=5, random_state=0).fit(X_minmax)
# center of each clusters
centers = kmeans2.cluster_centers_
# labels of each datapoint
labels2 = kmeans2.labels_
# distance between datapoint and cluster
distance = kmeans2.fit_transform(X_minmax)

In [34]:
centers

array([[0.5 , 0.16, 0.31, 0.5 , 0.25],
       [0.5 , 0.83, 0.75, 0.5 , 0.52],
       [0.5 , 0.85, 0.26, 0.5 , 0.43],
       [0.5 , 0.16, 0.8 , 0.5 , 0.5 ],
       [0.5 , 0.26, 0.31, 0.5 , 0.8 ]])

In [35]:
df['Labels_Cluster'] = labels2

In [38]:
distance_data = pd.DataFrame(data=distance, columns=['Dist_Cluster_Revenue', 'Dist_Cluster_Category', 'Dist_Cluster_lenghtDiscount', 'Dist_Cluster_Quantity', 'Dist_Cluster_NormalPrice'])

In [40]:
distance_data.shape

(284260, 5)

In [60]:
distance.shape

(284260, 5)

In [61]:
df.shape

(284260, 38)

In [73]:
data = pd.concat([df, distance_data], axis=1)

In [74]:
data.shape

(284260, 43)

In [75]:
data.columns.sort_values().values

array(['AbandonedCart', 'AcceptAD', 'AcceptDiscount', 'AddtoCart',
       'BuyOrNot', 'Category', 'Churn', 'Clustering',
       'CompetitionPressure', 'Country', 'CustomerID', 'Date',
       'DaysLastOrder', 'Description', 'Display', 'DisplayInStore',
       'Dist_Cluster_Category', 'Dist_Cluster_NormalPrice',
       'Dist_Cluster_Quantity', 'Dist_Cluster_Revenue',
       'Dist_Cluster_lenghtDiscount', 'Elasticity', 'InvoiceDate',
       'InvoiceNo', 'KindOfSale', 'Labels_Cluster', 'LenghtDiscount',
       'NormalPrice', 'One_Hot_Category', 'Payment', 'PromotionDays',
       'Quantity', 'ReOrder', 'RePurchase', 'Revenue', 'Seasonality',
       'StockCode', 'Time', 'TypeofProduct', 'TypeofPromotion',
       'UnitPrice', 'Weather', 'day_of_week'], dtype=object)

In [76]:
conditions = [
    (data['Labels_Cluster'] == 0),
    (data['Labels_Cluster'] == 1),
    (data['Labels_Cluster'] == 2),
    (data['Labels_Cluster'] == 3),
    (data['Labels_Cluster'] == 4)]
    
choices = ['Defensor', 'Shopper', 'Eventual', 'Regular', 'Prospect']
data['Labels_Cluster_Name'] = np.select(conditions, choices, default='black')



In [77]:
data.columns.sort_values()

Index(['AbandonedCart', 'AcceptAD', 'AcceptDiscount', 'AddtoCart', 'BuyOrNot',
       'Category', 'Churn', 'Clustering', 'CompetitionPressure', 'Country',
       'CustomerID', 'Date', 'DaysLastOrder', 'Description', 'Display',
       'DisplayInStore', 'Dist_Cluster_Category', 'Dist_Cluster_NormalPrice',
       'Dist_Cluster_Quantity', 'Dist_Cluster_Revenue',
       'Dist_Cluster_lenghtDiscount', 'Elasticity', 'InvoiceDate', 'InvoiceNo',
       'KindOfSale', 'Labels_Cluster', 'Labels_Cluster_Name', 'LenghtDiscount',
       'NormalPrice', 'One_Hot_Category', 'Payment', 'PromotionDays',
       'Quantity', 'ReOrder', 'RePurchase', 'Revenue', 'Seasonality',
       'StockCode', 'Time', 'TypeofProduct', 'TypeofPromotion', 'UnitPrice',
       'Weather', 'day_of_week'],
      dtype='object')

In [78]:
data.to_csv('retail_july3.csv', index=False)

In [ ]:
 Prospect : é um cliente que pode estar interessado em comprar da sua empresa
Shopper : são aqueles que visitam o seu negócio pelo menos uma vez
Cliente eventual : são pessoas que adquiriram um ou mais produtos da sua empresa
Cliente regular : são os que adquirem periodicamente seus produtos e serviços
Defensor :

In [53]:
data.dropna(inplace=True)

In [54]:
data.isnull().sum()

AbandonedCart                  0
AcceptAD                       0
AcceptDiscount                 0
AddtoCart                      0
BuyOrNot                       0
Category                       0
Churn                          0
Clustering                     0
CompetitionPressure            0
Country                        0
CustomerID                     0
Date                           0
DaysLastOrder                  0
Description                    0
Display                        0
DisplayInStore                 0
Dist_Cluster_Category          0
Dist_Cluster_NormalPrice       0
Dist_Cluster_Quantity          0
Dist_Cluster_Revenue           0
Dist_Cluster_lenghtDiscount    0
Elasticity                     0
InvoiceDate                    0
InvoiceNo                      0
KindOfSale                     0
Labels_Cluster                 0
LenghtDiscount                 0
NormalPrice                    0
One_Hot_Category               0
Payment                        0
PromotionD

In [55]:
data.shape

(0, 44)

In [50]:
data.to_csv('retail_july3.csv', index=False)

In [8]:
from sklearn import preprocessing
scaler = preprocessing.StandardScaler()


In [9]:
# Standard Scaler
scaled_X = scaler.fit_transform(X)

In [10]:
scaled_X

array([[-0.02545157, -1.34256712,  1.02213817, -0.03306256,  0.83178112],
       [-0.0048317 ,  0.44616737,  1.1195026 , -0.03306256, -1.47389283],
       [ 0.00195977,  0.44616737, -1.44556528, -0.02320742, -0.54652127],
       ...,
       [-0.06247733, -0.44819988,  0.71439534, -0.05770039,  0.89248359],
       [-0.05736328,  1.34053461,  1.61742131, -0.05770039, -0.83487508],
       [-0.06779595, -0.44819988, -0.06550947, -0.05770039, -1.26916871]])

In [11]:
kmeans = KMeans(n_clusters=5, random_state=0).fit(scaled_X)

In [12]:
#Neste momento já temos os dados agrupados e vamos verificar os centroides gerados 
#através do atributo cluster_centers_.

a = kmeans.cluster_centers_
np.set_printoptions(precision=2)
print(a)

[[-1.41e-03  9.46e-01 -6.13e-01 -1.12e-03 -2.99e-03]
 [ 3.16e+02 -1.34e+00 -2.84e-01  3.66e+02  6.76e-01]
 [-3.16e+02  1.34e+00 -1.40e+00 -3.66e+02 -6.61e-01]
 [-3.76e-04 -1.03e-02  1.07e+00  1.32e-04  6.08e-03]
 [ 1.87e-03 -9.46e-01 -6.31e-01  9.85e-04 -4.05e-03]]


In [13]:
# predict new data to match clustering
kmeans.predict(X)

array([3, 3, 3, ..., 3, 3, 3], dtype=int32)

In [14]:
# O método fit_transform() executa o K-means para agrupar os dados e retorna uma tabela de distâncias.
# A tabela de distâncias é criada de forma que em cada instância contém os valores de distância em relação a cada cluster.
distance = kmeans.fit_transform(X)
distance.shape

(284260, 5)

In [15]:
min_max_scaler = preprocessing.MinMaxScaler()
X_minmax = min_max_scaler.fit_transform(X)
X_minmax

array([[0.5 , 0.  , 0.8 , 0.5 , 0.74],
       [0.5 , 0.67, 0.82, 0.5 , 0.07],
       [0.5 , 0.67, 0.08, 0.5 , 0.34],
       ...,
       [0.5 , 0.33, 0.71, 0.5 , 0.76],
       [0.5 , 1.  , 0.97, 0.5 , 0.26],
       [0.5 , 0.33, 0.48, 0.5 , 0.13]])

In [16]:
kmeans2 = KMeans(n_clusters=5, random_state=0).fit(X_minmax)
# center of each clusters
b = kmeans2.cluster_centers_
# labels of each datapoint
labels2 = kmeans2.labels_
# distance between datapoint and cluster
distance = kmeans2.fit_transform(X_minmax)


In [17]:
b = kmeans2.cluster_centers_


In [19]:
labels2 = kmeans2.labels_

In [20]:
labels = kmeans.labels_

In [28]:
labeled = pd.DataFrame({'labels_std': labels, 'labels_min_max': labels2})

In [29]:
labeled

labels_std  labels_min_max
0                0               3
1                0               1
2                0               2
3                0               0
4                0               0
5                0               4
6                0               1
7                0               2
8                0               0
9                0               0
10               0               3
11               0               3
12               0               2
13               0               1
14               0               3
15               0               0
16               0               1
17               0               1
18               0               4
19               0               4
20               0               2
21               0               0
22               0               3
23               0               2
24               0               2
25               0               3
26               0               1
27               0               3
28               0               3
29               0               3
...            ...             ...
284230           0               1
284231           0               2
284232           0               3
284233           0               3
284234           0               3
284235           0               3
284236           0               4
284237           0               2
284238           0               0
284239           0               2
284240           0               4
284241           0               1
284242           0               2
284243           0               2
284244           0               1
284245           0               1
284246           0               1
284247           0               2
284248           0               2
284249           0               1
284250           0               0
284251           0               1
284252           0               1
284253           0               4
284254           0               0
284255           0               0
284256           0               2
284257           0               3
284258           0               1
284259           0               0

[284260 rows x 2 columns]

In [22]:
pd.Series(list((labels2).intersection((labels))))

AttributeError: 'numpy.ndarray' object has no attribute 'intersection'

In [23]:
def overlap_mbk(a, b):
    a1=np.argsort(a)
    b1=np.argsort(b)
    # use searchsorted:
    sort_left_a=a[a1].searchsorted(b[b1], side='left')
    sort_right_a=a[a1].searchsorted(b[b1], side='right')
    #
    sort_left_b=b[b1].searchsorted(a[a1], side='left')
    sort_right_b=b[b1].searchsorted(a[a1], side='right')


    # # which values are in b but not in a?
    # inds_b=(sort_right_a-sort_left_a == 0).nonzero()[0]
    # # which values are in b but not in a?
    # inds_a=(sort_right_b-sort_left_b == 0).nonzero()[0]

    # which values of b are also in a?
    inds_b=(sort_right_a-sort_left_a > 0).nonzero()[0]
    # which values of a are also in b?
    inds_a=(sort_right_b-sort_left_b > 0).nonzero()[0]

    return a1[inds_a], b1[inds_b]

In [24]:
ind_a, ind_b = overlap_mbk(labels, labels2)

In [25]:
ind_a

array([     0, 189498, 189499, ...,  38120, 159240, 159239])

In [26]:
ind_b

array([142129, 121783, 121781, ...,  54415, 160660,  52240])