In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('retail_may.csv')

In [3]:
df.dropna(inplace=True)

In [4]:
df.to_csv('retail_june.csv', sep=',')

In [5]:
df.isnull().sum()

InvoiceNo              0
StockCode              0
Description            0
Quantity               0
InvoiceDate            0
UnitPrice              0
CustomerID             0
Country                0
AcceptDiscount         0
NormalPrice            0
LenghtDiscount         0
day_of_week            0
PromotionDays          0
Elasticity             0
KindOfSale             0
Display                0
DisplayInStore         0
TypeofPromotion        0
TypeofProduct          0
CompetitionPressure    0
Seasonality            0
Category               0
Time                   0
Date                   0
Payment                0
Revenue                0
Clustering             0
Weather                0
dtype: int64

In [6]:
X = df.drop(['AcceptDiscount'], axis=1)

In [7]:
X = X.select_dtypes(include=['int', 'float'])
y = np.array(df[['AcceptDiscount']]).ravel()

In [8]:
y

array([0, 1, 0, ..., 1, 1, 1])

In [9]:
X.columns

Index(['Quantity', 'UnitPrice', 'CustomerID', 'NormalPrice', 'LenghtDiscount',
       'PromotionDays', 'Elasticity', 'KindOfSale', 'Display',
       'DisplayInStore', 'TypeofPromotion', 'TypeofProduct',
       'CompetitionPressure', 'Seasonality', 'Revenue', 'Clustering'],
      dtype='object')

     """
        Parameters
        -----------        
        treatment : array-like
            binary treatment assignment
        covariates : pd.DataFrame
            covariates, one row for each observation
        """

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [11]:
from pscore_match.pscore import PropensityScore

In [12]:
y

array([0, 1, 0, ..., 1, 1, 1])

In [13]:
treatment = y
covariates = X

In [14]:
covariates

Quantity  UnitPrice  CustomerID  NormalPrice  LenghtDiscount  \
0              6       2.55     17850.0    14.795989        8.162408   
1              6       3.39     17850.0     1.497314        8.415264   
2              8       2.75     17850.0     6.846211        1.753776   
3              6       3.39     17850.0     1.825050        2.214386   
4              6       3.39     17850.0    10.688266        4.782673   
5              2       7.65     17850.0    13.595531        3.471170   
6              6       4.25     17850.0     8.697515        5.699631   
7              6       1.85     17850.0     6.550380        3.838285   
8              6       1.85     17850.0     5.843938        3.333459   
9             32       1.69     13047.0     7.945071        3.825552   
10             6       2.10     13047.0     3.838989        9.708583   
11             6       2.10     13047.0     4.257777        9.440400   
12             8       3.75     13047.0     7.934462        5.180662   
13             6       1.65     13047.0     4.367577        5.940750   
14             6       4.25     13047.0    13.939915        6.772174   
15             3       4.95     13047.0     2.579155        2.552955   
16             2       9.95     13047.0     2.935470        8.738376   
17             3       5.95     13047.0     5.343338        8.113448   
18             3       5.95     13047.0    17.128514        6.471736   
19             4       7.95     13047.0    16.931380        4.042610   
20             4       7.95     13047.0     1.731468        4.321124   
21             6       4.25     13047.0     2.431907        4.214690   
22             3       4.95     13047.0     8.203062        7.494653   
23             3       4.95     13047.0    10.791018        3.229542   
24             3       4.95     13047.0     3.167542        5.198217   
25             3       5.95     13047.0     3.291668        9.952873   
26            24       3.75     12583.0     9.111126        8.061399   
27            24       3.75     12583.0    17.991036        7.889066   
28            12       3.75     12583.0    11.551573        8.992378   
29            12       0.85     12583.0     8.616868        7.736084   
...          ...        ...         ...          ...             ...   
384160        12       1.45     13004.0    14.724701        8.468375   
384161        10       0.85     13004.0     8.556426        2.304514   
384162         6       2.08     13004.0     4.252354        8.868539   
384163         8       1.95     13004.0    17.535081        7.143792   
384164        20       0.42     13004.0     1.603953        8.231383   
384165         6       3.75     13004.0    18.972230        9.962920   
384166         4       5.95     13004.0    13.759447        5.415371   
384167         6       3.75     13004.0    16.209991        2.057567   
384168         6       3.75     13004.0     6.651597        4.623744   
384169         6       3.75     13004.0    16.396571        4.972253   
384170        16       0.65     13004.0    11.238049        1.455072   
384171        16       0.65     13004.0     9.817639        6.491658   
384172        16       0.65     13004.0     9.352518        1.500466   
384173        20       0.42     13004.0    13.216928        1.658780   
384174        10       1.95     13004.0    10.370582        5.730026   
384175         4       5.95     13004.0     3.054080        9.843900   
384176         2       8.25     13004.0    14.543194        6.353694   
384177         2       8.25     13004.0    19.233764        1.780148   
384178        24       0.55     13004.0     5.866192        2.359094   
384179        12       0.42     13004.0     5.566649        7.610205   
384180        24       0.55     13004.0     3.448031        1.040129   
384181        12       0.85     13004.0     4.725964        8.779045   
384182        12       1.65     13004.0     9.291222        9.808790   
384183         6       2.10     13004.0    16.33

In [15]:
treatment = np.array(y)

In [16]:
treatment

array([0, 1, 0, ..., 1, 1, 1])

In [17]:
pscore = PropensityScore(treatment, covariates).compute()


In [18]:
from pscore_match.match import Match, whichMatched
from scipy.stats import gaussian_kde
import matplotlib.pyplot as plt
pairs = Match(treatment, pscore)
#pairs.create(method='many-to-one', many_method='knn', k=5, replace=True)


In [19]:
covariates = np.array(covariates)

In [20]:
data_matched = whichMatched(pairs, pd.DataFrame({'pscore': pscore, 'treatment' :treatment}))

AttributeError: 'Match' object has no attribute 'freq'

In [ ]:
data_matched

In [ ]:
a = PropensityScore(y_train, X_train)

In [ ]:
match = a.compute()

In [ ]:
X_train.shape

In [ ]:
match.shape

In [ ]:
match.min()

In [ ]:
match.max()

In [ ]:
match.argmin

In [ ]:
#from pscore_match.data import gerber_green_imai
#from pscore_match.pscore import PropensityScore
from pscore_match.match import Match, whichMatched
from scipy.stats import gaussian_kde
import matplotlib.pyplot as plt
#import numpy as np
#import pandas as pd

imai = gerber_green_imai()

# Create interaction terms
imai['PERSONS1_VOTE961'] = (imai.PERSONS==1)*imai.VOTE961
imai['PERSONS1_NEW'] = (imai.PERSONS==1)*imai.NEW
treatment = np.array(imai.PHNC1)
cov_list = ['PERSONS', 'VOTE961', 'NEW', 'MAJORPTY', 'AGE', 'WARD', 'AGE2',
                            'PERSONS1_VOTE961', 'PERSONS1_NEW']
covariates = imai[cov_list]
pscore = PropensityScore(treatment, covariates).compute()

pairs = Match(treatment, pscore)
pairs.create(method='many-to-one', many_method='knn', k=5, replace=True)
data_matched = whichMatched(pairs, pd.DataFrame({'pscore': pscore, 'treatment' :treatment, 'voted':imai.VOTED98}))